-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 17-03-2024 a las 11:02:52
-- Versión del servidor: 10.4.32-MariaDB
-- Versión de PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `proyecto`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `uuid` varchar(255) NOT NULL,
  `connection` text NOT NULL,
  `queue` text NOT NULL,
  `payload` longtext NOT NULL,
  `exception` longtext NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(29, '2014_10_12_000000_create_users_table', 1),
(30, '2014_10_12_100000_create_password_reset_tokens_table', 1),
(31, '2019_08_19_000000_create_failed_jobs_table', 1),
(32, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(33, '2024_03_06_233404_create_posts_table', 1);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `password_reset_tokens`
--

CREATE TABLE `password_reset_tokens` (
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `password_reset_tokens`
--

INSERT INTO `password_reset_tokens` (`email`, `token`, `created_at`) VALUES
('cesaralvarezuchiha3@gmail.com', '$2y$12$yDd9wSYXsysAld3w501sXOgk1TEY0F4ocgalpy1G5iFDRk9WCoYvu', '2024-03-16 23:01:37');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `personal_access_tokens`
--

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `tokenable_type` varchar(255) NOT NULL,
  `tokenable_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `token` varchar(64) NOT NULL,
  `abilities` text DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `posts`
--

CREATE TABLE `posts` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `posts`
--

INSERT INTO `posts` (`id`, `user_id`, `title`, `slug`, `body`, `created_at`, `updated_at`) VALUES
(1, 1, 'Eveniet enim aliquid fugiat quibusdam hic magnam accusamus.', 'eveniet-enim-aliquid-fugiat-quibusdam-hic-magnam-accusamus', 'Non dolorem eaque consequatur dolor. Eligendi debitis libero eaque ut. Aut aperiam sint vitae et autem aut debitis. Rem est sint unde incidunt est eum nemo aut. Molestiae rerum ea totam nulla. Ab eaque impedit ea sunt ut ducimus. Velit ea voluptas enim dolorem pariatur sequi. Sequi soluta enim doloremque odio porro. Aut impedit mollitia esse facilis. Consequatur eos quibusdam exercitationem optio laborum. Consequatur laboriosam voluptatem asperiores assumenda at. Dolor culpa eos sit. Deleniti in ad aut. Facilis quis consectetur aspernatur sint. Similique cum non quia et voluptate possimus et. Quod voluptates expedita et. Aperiam et reprehenderit quia omnis iusto exercitationem. Ad rem quod at ullam velit ratione. Officiis nam aut saepe asperiores soluta delectus sed. Esse animi nihil architecto laboriosam voluptas. Voluptas maxime aperiam est nihil quia officia et autem. Eligendi doloribus unde et. Quia sit vel cupiditate et eligendi. Amet culpa architecto debitis consequatur. Aut eum aliquid qui voluptates. Eos neque beatae voluptatem inventore. Atque sed quia sint. Aut et animi excepturi nobis et. Ut sed unde nulla accusantium. Nisi autem sunt esse mollitia dignissimos vero voluptates. At dolorum et beatae tempore quia ut. Autem adipisci officiis repellat vel quia aut assumenda aut. Blanditiis repellendus sed in voluptatem. Nostrum quae blanditiis nam cum illo. Quia labore totam rerum qui quia. Et eum quisquam amet expedita quo sapiente. Repudiandae veritatis consequatur facere sunt quam. Sunt nulla doloribus cum fugit minus provident beatae. Atque minima enim similique architecto maiores et est mollitia. Quaerat porro a maiores neque modi aliquid adipisci. Deserunt aut aut at dolor non culpa culpa. Quia ad amet ipsum accusantium. Tempora saepe voluptas tempore et qui commodi. Qui ullam distinctio corporis dolor et. Architecto minima ea commodi in et aliquam ad. Illum modi officiis unde suscipit. Sint laborum aperiam eos ab laboriosam in sint. Rerum harum consequatur deserunt ab earum. Eum omnis voluptas numquam fugit et nihil ut optio. Minus aliquid beatae vel quia sint sit corporis. Enim sit sint voluptate delectus sit totam modi et.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(3, 1, 'Esse debitis nemo molestiae consequatur.', 'esse-debitis-nemo-molestiae-consequatur', 'Porro repudiandae odio perferendis est sapiente. Vitae amet occaecati minima recusandae quia et. Nesciunt fugiat officia similique vel deleniti suscipit. Amet rerum maxime qui est quia itaque. Optio molestias sunt dolorem quam sit. Debitis error illo et esse optio et deserunt. Aspernatur qui debitis voluptatibus eos ipsam. Inventore facere voluptas quos sed. Voluptatem numquam ipsum mollitia inventore voluptas accusantium ut. Libero ex libero quia quidem laboriosam. Expedita quisquam quibusdam aut. Adipisci reiciendis optio sit porro. Et excepturi beatae non optio voluptatem aut delectus asperiores. Ut vero autem eum molestias at dolores. Quisquam atque iusto aspernatur vel deserunt. Temporibus recusandae dolorem assumenda tenetur. Et fugit minima et dolore. Numquam unde dolores illum et expedita deserunt omnis facilis. Dolorem possimus earum eaque provident iure. Sunt non ipsam est eaque dolore. Sit aliquid vel sint ducimus omnis aut qui. Doloremque libero nihil est animi voluptatem. Et voluptas exercitationem illum quaerat. Consequatur molestias recusandae distinctio et. Quae reiciendis ipsam consequatur vitae libero voluptate similique. Officiis cupiditate est deserunt nesciunt deserunt cum. Enim porro rerum fuga maiores. Quis dolores voluptas sit dolorum. Unde nemo voluptate architecto similique. Debitis et quis laudantium minima molestiae quas sit. Hic amet non quia. Officia doloribus maiores temporibus delectus aliquam consequuntur. Illum ducimus qui veritatis tempore iste libero nihil laudantium. Delectus ex assumenda molestias quos. Et delectus dolorem et nisi ut rerum consequatur. Ipsum nesciunt et aliquid consequatur. Ut repellendus culpa id perferendis repudiandae sint. Quo nesciunt quo deserunt enim. Beatae optio accusamus expedita et. Labore iusto vero dolor sequi et id. Temporibus ut voluptatum ullam perferendis nulla at. Nihil officiis dolorum voluptatibus recusandae rerum officiis. Magni dignissimos autem ipsum. Tenetur inventore dignissimos qui et in atque aut. Dolor dolores doloribus nulla et. Et minus id voluptas. Ex dolorem id beatae qui. Itaque nulla nesciunt rerum similique eos ex. Consequatur placeat aut aliquam atque.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(4, 1, 'Dolores odio placeat vel molestiae.', 'dolores-odio-placeat-vel-molestiae', 'Laudantium quia dignissimos eligendi est et. Optio voluptas et labore dolorum dicta. Sequi sit rerum magnam facilis earum. Laboriosam assumenda dolore doloribus autem id minus quis. Beatae illum mollitia et. Delectus eligendi veniam consequatur et alias expedita. Consequatur repellat sit nesciunt voluptas aliquam reprehenderit. Omnis ut alias placeat repellendus est. Enim illum et dicta pariatur. Id ut illum blanditiis aut est omnis quod. Sit nihil voluptatem iste voluptatem enim consequuntur. Blanditiis quia officia ea nihil beatae repellendus natus. Beatae minima id eveniet eum mollitia sed distinctio ad. Eum sint voluptas accusantium vel omnis dolorem sequi. Dolorem quia et rerum. Magni omnis fuga ipsam sed tenetur. Voluptatem repellat deleniti tempore aut nobis voluptatem praesentium. Suscipit voluptatem in quod ut numquam eos quas. Non ipsam et nisi qui expedita molestias. Qui quasi sapiente doloremque et totam. Cumque necessitatibus dolorem officia ipsam dolore. Illum reprehenderit ullam debitis ad quaerat consequuntur. Eum non nihil laudantium optio. Repellat quisquam voluptatibus numquam autem at occaecati. Omnis nihil aut repellat voluptatem laboriosam esse. Odit blanditiis facere nemo reiciendis et aspernatur sit. Qui iste sed consequatur qui eos neque laboriosam. Dolor dolorem dolor tenetur totam sed illo. Est ipsam aut porro consequatur voluptas. Fuga voluptates maiores reiciendis nobis odit dolor consequatur. Velit perferendis consequatur est qui. Reprehenderit corrupti exercitationem quaerat est nemo. Velit ex sint quasi voluptatem nihil quae rem. Quo earum fuga sint vel delectus saepe quibusdam. Eveniet officiis voluptatem quibusdam suscipit. Voluptas qui blanditiis atque dignissimos voluptates molestias et quia. Qui at molestiae minus qui enim et. Occaecati tempore dolor dolor rerum. Perspiciatis ipsum sed mollitia sed qui debitis. Placeat sed esse quia illum ex. Dolorum quibusdam alias officiis rerum voluptatem est aut. Laborum tenetur culpa similique ullam at omnis. Deserunt ut quis et autem maxime maiores. Magni natus ex ut est dolor.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(5, 1, 'Iste rem eos eos odit non ducimus ut.', 'iste-rem-eos-eos-odit-non-ducimus-ut', 'Neque id officiis animi debitis ab earum. Nostrum ratione aut hic voluptatem. Voluptate laboriosam sit fuga aliquid. Et est nihil officiis qui delectus. Maxime consequatur et atque aperiam. Voluptas quae perferendis beatae dicta et alias. Vitae consequuntur quia expedita numquam deserunt. Quis voluptates odit ea consequuntur. Vero a molestiae commodi nostrum sit rerum. Enim vel aut natus quasi natus. Optio dignissimos repellat et doloremque. Et nostrum aut sequi maiores molestiae et et voluptas. A officiis perferendis quo et dicta. Perspiciatis nulla distinctio nostrum perferendis et odit. Quae officiis dolores voluptas. Error nobis quam ducimus quis eveniet. Facere voluptas accusamus enim molestiae voluptatem. Eum atque deserunt qui similique optio qui. Maiores et alias numquam porro laudantium. Excepturi et deleniti dolores. Culpa amet blanditiis ducimus omnis ipsa laboriosam. Rem neque minima eum maiores. Facere dolorem omnis tempore ut laudantium et maiores. A dolores totam harum enim non in aut. Rerum rerum saepe amet vel autem odit sed et. Aliquam ut voluptas labore culpa. Quisquam quam odit mollitia dolore. Ad voluptas recusandae aut dolorem soluta quam sit. Sunt voluptatem suscipit libero rem. Tempore similique suscipit vel ea. Quidem beatae distinctio minima molestiae ut ut. Praesentium consequatur eos exercitationem neque cum soluta reprehenderit quos. Accusamus laboriosam fuga quo qui eum qui sit. Voluptatem velit omnis beatae cupiditate possimus dicta minima numquam. Deleniti ea maiores sunt ducimus sed totam. Alias qui tenetur et. Dolores velit eveniet voluptate cum animi voluptate consequatur dicta. Architecto amet minus aut voluptatem cum adipisci dolorum sunt. Cum repudiandae praesentium voluptate aspernatur voluptatem. Et aut quia sed blanditiis velit doloremque molestiae. Numquam tenetur quia eum qui eligendi. Sit eum veritatis molestias distinctio nisi veniam. Doloremque sed aut est laborum. Vero sapiente quia nisi itaque omnis sit non. Illo corrupti ullam aut et. Cum corrupti ad minima eum cupiditate.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(6, 1, 'Magni aut ea doloremque quia.', 'magni-aut-ea-doloremque-quia', 'Animi omnis quidem quidem asperiores alias voluptates labore ea. Reprehenderit non adipisci illum quae consectetur quis fuga occaecati. Sint et et architecto a sint veritatis voluptate. Dolor laborum iste nesciunt aut doloribus dolorem. Nobis libero ea nihil nihil aperiam dolor. Quaerat delectus corrupti similique aut laborum quia. Quibusdam minima quae veritatis. Qui ipsum iusto dolorum. Id odio commodi est odio ipsum quisquam repudiandae consequatur. Quisquam sit libero magni labore dolores. Omnis reprehenderit error inventore autem. Voluptatibus non corporis iure quis soluta aspernatur mollitia voluptatum. Fuga sint mollitia nulla consequatur. Repellendus mollitia ab ducimus delectus velit. Error in hic iure magnam. Minus corrupti sed est aut adipisci et. Vitae dolorum in voluptatem. Numquam praesentium cum optio praesentium porro. Quibusdam quo laborum temporibus aut et. Possimus labore rerum doloremque vel saepe sapiente et. Est animi dolore ea magni ratione esse dolorum est. Tempora quia sed possimus magni impedit eligendi. Delectus velit vitae soluta sequi mollitia. Fuga a commodi pariatur nisi est ut quod. Et tenetur explicabo quo ullam. Consequatur officia sit veniam ab veniam. Perspiciatis repellat non sint quia alias inventore dolores. Suscipit recusandae doloremque maxime ratione. Est ab voluptas eligendi. Non amet recusandae ut. Nam quia nam esse explicabo. Ipsa veniam quos repellendus ut facere. Maiores repudiandae laboriosam ullam voluptatem aliquid illum et. Voluptate atque et voluptas qui. Sed eos iure animi vitae incidunt quia saepe. Architecto et dolores aliquid maxime vero porro. Expedita voluptas ea eos ut culpa velit. Veritatis aut dolorem et et velit iusto. Et aut repellendus sint est. Voluptatem quae eos aut eaque repellendus. Labore autem quaerat non adipisci. Et nihil qui non qui aperiam. Ut in saepe vitae assumenda doloremque eum est rerum. Facere placeat corporis natus quia. Deserunt harum ad saepe ratione sed voluptas. Corrupti commodi id repellat amet. Reiciendis eos consequatur est accusamus qui pariatur porro. Pariatur voluptatibus qui cum qui culpa recusandae blanditiis.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(7, 1, 'Minima modi et rem fugiat ipsam.', 'minima-modi-et-rem-fugiat-ipsam', 'Ipsum voluptatibus nisi nisi. Qui dolor voluptatem odit aperiam magni suscipit. Qui libero laborum totam id. Ab placeat nobis eveniet asperiores eos. Exercitationem tempora voluptas est officiis facere. Id id molestias consequuntur aut. Dolores perspiciatis dignissimos omnis eius. Porro magni molestiae inventore illum. Veritatis omnis quaerat veniam doloribus deleniti impedit. Sunt consequuntur cumque qui maiores facere eos veniam sapiente. Voluptas officiis ad expedita quisquam saepe aperiam. Dolorem atque occaecati velit molestias ipsam. Non nihil dolorum sit quam illum deserunt fugiat. Fugit cumque odit debitis sunt qui et. Et velit consequatur sint mollitia. Consequatur eligendi optio dolorem explicabo. Iure fugiat aut eius beatae voluptas repellendus necessitatibus. Ex animi beatae omnis suscipit ipsum error ut. Atque quia sunt eaque sed eos voluptate quo. Voluptates minima occaecati quia odit laudantium officiis. Voluptas perspiciatis explicabo aspernatur quia consectetur eum dolorem. Et amet non exercitationem non quam aut saepe. Qui asperiores laudantium veniam odio et non et. Voluptatibus error velit ut autem. Eos repellat atque facilis nihil. Aut quae est officia officia. Quas occaecati ea aliquam eos eius sunt perferendis. In eaque omnis quis voluptas id facilis. Sed similique et odio vel consequatur et dolor ut. Asperiores et assumenda pariatur est harum sit occaecati iusto. Et corporis assumenda vitae explicabo voluptas explicabo nulla voluptates. Vero numquam recusandae laborum deleniti. Rerum qui omnis quia esse dolorum ipsam enim. Aut qui saepe tenetur soluta maxime consequatur. Voluptas ut recusandae voluptatem quasi accusamus. Accusamus deleniti qui quis est dolor iste. Ut dolore est asperiores iusto qui nostrum vel. Incidunt tempora voluptatum id iure. Voluptas dolor porro ipsa sit exercitationem possimus atque. Ex tempore deserunt et aspernatur repudiandae magnam asperiores. Provident voluptatem fugiat sit est odit. Ducimus repudiandae aperiam veritatis totam mollitia explicabo. Neque omnis quod iste omnis et. Nesciunt nisi perferendis commodi et voluptas reprehenderit quo. Optio quis eum accusamus occaecati suscipit amet pariatur.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(8, 1, 'Neque illo omnis blanditiis ut est laborum quas vel.', 'neque-illo-omnis-blanditiis-ut-est-laborum-quas-vel', 'Vitae fuga voluptas consequatur enim dignissimos. Illo atque aut ipsa. Libero nostrum id consequatur quos repellendus veniam. Minus eaque reprehenderit deleniti quam voluptatem doloremque. Quisquam soluta voluptatum qui quibusdam et in. Magnam cupiditate et ex qui non architecto est. Omnis aliquam natus sed magni deleniti ipsa. Ad consectetur aliquam sint veniam fuga aut velit. Est omnis enim odio. Ipsam voluptas sunt dolor modi aut eos aut. Voluptatum excepturi nihil et totam. Et consequatur soluta odit cupiditate est voluptatum aut at. Doloribus id dolores dolor molestias soluta officiis. Totam exercitationem labore omnis sed labore odit in. Ullam ea accusamus esse modi error quia. Quia illum et voluptatem dolore molestiae ratione distinctio. Quod quaerat eius sed non. Eligendi in est maiores sit dolorum quia. Quis quia ad iure dolore eum saepe. Debitis minima quia facere natus nihil. Error quam corporis sunt vitae dolorem. Praesentium est dolorem veritatis. Officiis quos totam nobis molestiae et officiis natus natus. Id voluptatum velit rerum accusamus culpa sapiente corrupti. Autem ut soluta est at aut reiciendis in. Dolor mollitia necessitatibus molestias laborum provident unde et. Ut aut et atque aliquam culpa officiis quo. Magni aut ratione aut dolorum impedit totam. Ut qui maiores perferendis qui voluptas dolore. Quia aspernatur aut sint eius fuga placeat praesentium. Cum minima quod doloremque ad. Nulla rerum aut ad voluptas aut iusto. Fuga dolores vel rerum quos doloribus. Ducimus aspernatur non quia voluptatum similique id. Et deserunt quisquam omnis consectetur quo corrupti id ullam. Ea minima distinctio non assumenda et totam neque. Commodi error sit quis dolorum fuga dolores. Porro adipisci dignissimos dignissimos molestiae ipsa. Alias aut repellat consequatur minus quas eligendi asperiores. Necessitatibus laboriosam fuga dolores accusamus sed optio incidunt quibusdam. Quia dolorem ea et recusandae consectetur totam et. Aut quisquam autem velit error sunt. Aspernatur veniam aut voluptatem.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(9, 1, 'Dolorum est similique vel nihil.', 'dolorum-est-similique-vel-nihil', 'A optio consequatur excepturi. Vel est et accusamus voluptates. Ullam et quo nemo facilis doloremque ut. Vel quaerat et eius blanditiis. Voluptas nihil amet et nostrum. Adipisci rerum et omnis veniam recusandae ea error omnis. Et eos minima placeat et molestiae rem enim. Corporis dolores sit tempora quisquam quisquam autem nulla aspernatur. Aut adipisci voluptatem velit rerum. Dolore culpa neque et beatae accusantium. Quos est consequatur ad. Qui voluptatum voluptates odio qui vitae non sed dolore. Doloremque est vel dolores aut. Autem tenetur vel explicabo nihil facere ad. Magni dolorem animi asperiores. Vitae culpa ut quis asperiores facilis sunt. Voluptates eligendi minima saepe temporibus numquam dolorem libero. Optio vel magni voluptate voluptatum nesciunt non vitae. Possimus voluptatum sit provident repellat qui qui. Quisquam est ea cum nam sit ab. Consectetur dolor quis incidunt iusto architecto. Eligendi eveniet mollitia quam voluptatem consequuntur quibusdam consequuntur. Consectetur non praesentium culpa dolore est ducimus. Ad et ratione necessitatibus cupiditate quaerat. Deleniti architecto expedita sunt. Sapiente necessitatibus inventore tempora. Est facilis beatae tempora commodi suscipit eum. Sint fugit ex incidunt assumenda temporibus nobis. Libero non explicabo optio beatae reprehenderit asperiores aut. Eos exercitationem voluptas et non adipisci aspernatur. Minus dolor molestias tempore. Ex ipsam ea modi commodi fugiat. Dolores qui repudiandae eos quam quos sint at. Aspernatur aut esse rerum similique dolorum. Quos eveniet cum molestiae veritatis. Omnis vel est facere quibusdam sit. Fugit minus eos eius mollitia quo qui. Facilis aliquam illum magnam eos. Voluptatem aut id nobis cum fugit fugit quia. Eum non et dicta odio beatae adipisci et tempore. Modi odit in provident architecto optio. Non aut deleniti delectus. Corporis qui id molestiae nemo est laborum praesentium et. Vitae expedita dolor sequi qui a reiciendis corrupti. Expedita delectus aut laborum delectus qui nostrum et. Vel cumque quas eos cupiditate. In exercitationem est voluptatem earum est. Nesciunt amet sed blanditiis in. Veritatis fuga molestias rerum sit.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(10, 1, 'Quia dolore alias at dolorem possimus.', 'quia-dolore-alias-at-dolorem-possimus', 'Sed quae magni odio molestiae nihil exercitationem non. Error odio velit modi quod. Quis hic voluptates veniam expedita possimus quis et aut. Fugiat nihil inventore ut harum. Eum quia aut incidunt ut enim. Ab accusantium molestiae quam mollitia. Fugiat impedit qui eos laboriosam cumque ipsam accusamus. Voluptates unde magnam sapiente quas. Ea beatae iste et tenetur vitae deleniti provident. Quas eligendi et omnis ducimus blanditiis. Adipisci explicabo nihil quod et. Voluptatem rerum consequatur unde magni. Corrupti nulla voluptatem necessitatibus mollitia velit consequatur eligendi. Similique error illo sint quo aliquam. Aut labore sunt ducimus alias hic officiis quos. Quis quam sint at omnis. Et eos sit ipsam omnis odit tempora qui. Omnis necessitatibus voluptatem quo dolor sunt tempore. Iusto repellendus aspernatur qui nihil est. Molestiae minima vitae at ipsum. Qui rerum ut veniam consequatur. Dolores facilis tenetur vitae eligendi accusamus sit. Quia sed quo nisi officia qui. Quidem sed optio distinctio est repudiandae. Omnis at culpa sit reiciendis architecto. Sunt sequi eveniet sunt laboriosam qui. Sit nam consectetur incidunt dolorem similique possimus. Totam quaerat ut quo nostrum excepturi asperiores. Et vero quis eum. Et adipisci est aut itaque nobis eligendi ipsa. Nihil minima aliquam dolor deleniti cum sit. Aut dolorum sunt nemo quia sit id dolorum et. Nisi corrupti in aperiam. Quis totam asperiores quia ducimus fuga molestiae sint. Magnam tempora quidem perspiciatis et vel. Assumenda quod iure at officia quas eaque velit quis. Vero occaecati sint quis. Enim voluptates eveniet dolore molestiae quaerat. Quasi omnis assumenda quis. Rerum mollitia omnis maxime deleniti eos ipsa praesentium. Dolores sunt illum assumenda libero culpa. Porro eum fuga ullam laborum. Quaerat voluptatem ut reprehenderit reiciendis animi itaque. Ut non enim fugiat inventore exercitationem aut. Sed asperiores vel fugiat voluptatem commodi enim. Nisi eaque et possimus adipisci enim fuga. Aperiam quaerat quos sit rerum quo velit officia. Reiciendis aut dolores dolorem ea ab ipsa.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(11, 1, 'Omnis adipisci reiciendis labore.', 'omnis-adipisci-reiciendis-labore', 'Eaque voluptatum necessitatibus ut labore quas qui. Est vitae laudantium iusto ipsa vel rerum dolores. Explicabo autem odio provident aliquam. Dolorem amet eum deleniti quia. Sed hic et provident quo iste consequuntur alias velit. Eaque consequuntur nihil laudantium necessitatibus maiores. Aut aut consequuntur laboriosam et tenetur. Aut blanditiis omnis minima ad doloremque minima. Neque quidem quia ducimus provident voluptatem dicta. Voluptatum libero qui fugit qui consectetur similique. Inventore facilis velit molestias odit sed velit dolore eos. Odio error ea cum voluptas consequatur. Magnam aut quia eveniet autem aut nihil. Quia quo laboriosam voluptatem voluptatum. Accusamus tempore modi reiciendis quod rerum. Rem accusantium labore iusto maxime sapiente culpa nam. Nostrum quaerat corporis voluptas. Quo adipisci voluptates non quo. Deleniti in sit omnis beatae eligendi. Temporibus saepe ea eveniet molestias tempora inventore. Ut non aut consequatur voluptas molestiae temporibus. Ipsa dolores cupiditate et architecto eaque. Aliquam aspernatur sed maiores doloribus culpa. Non rem ipsa exercitationem exercitationem totam quo. Ut ipsum omnis porro maxime numquam unde. Qui laborum tempore sunt inventore. Voluptates in unde at voluptatum autem. Qui velit iure provident corrupti et. Hic qui deserunt deserunt suscipit deserunt nesciunt corporis. Fugiat velit magnam consequatur sunt et dolor assumenda. Et et amet ducimus. Eius quaerat enim nihil tempora sit illo. Dicta ab ratione voluptatem. Commodi dolor eum non magnam. Similique doloribus rem libero voluptatem. Minima pariatur ipsa et aut neque quibusdam. Omnis doloremque sed et reprehenderit. Ut qui quibusdam et rem aut corporis accusantium. Ullam sed temporibus qui. Est aliquam accusantium doloribus in. Maiores qui ipsam pariatur velit aut dolores animi. Iure explicabo esse vel ea quis. Itaque ipsa unde consequatur exercitationem laboriosam quo. Quia odit consequatur voluptas corporis. Vero culpa accusantium dolores dolor non quasi. Quia voluptatem dicta asperiores.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(12, 1, 'Iure autem sed rerum est.', 'iure-autem-sed-rerum-est', 'Excepturi quas quidem doloribus quia odio nisi laudantium autem. Rerum veniam eum dolores cupiditate quia. Ea dolor atque dolores et harum quis. Velit voluptatem inventore officiis optio eos ut omnis. Dolores aperiam omnis suscipit aut. Omnis rerum aperiam et error atque dolorem voluptatibus. Quis laboriosam optio porro perferendis quo quidem. Suscipit vitae non eos. Sapiente a atque enim aut recusandae aut voluptas. Non repudiandae itaque ad cumque cumque. Voluptate aspernatur ut id qui quibusdam qui similique placeat. Nam quod laudantium at sit. Omnis quae corporis non quasi molestiae ad at ullam. Saepe at ut minima voluptatem enim atque. Voluptas et ipsa ea voluptas voluptatem libero totam. Debitis mollitia cum pariatur eaque officia est. Cupiditate adipisci consequatur facilis ab non sit. Libero velit illo ducimus culpa ut omnis quam. Adipisci voluptas nam voluptatem enim minima assumenda harum. Rem itaque praesentium et blanditiis quis et repellendus. Quia cumque deserunt nostrum. Iure veniam veritatis consequatur eum inventore perspiciatis qui accusantium. Nisi eaque doloremque qui aut laboriosam magni. Iste illo odio sunt et maiores. Excepturi molestias quae dolores culpa ipsam beatae ipsa. Quae et earum consequatur nostrum. Et velit tempore aut fuga et ullam dolores. Quaerat itaque alias est ut aut. Accusantium aut ipsam id labore. Velit omnis ipsa rerum suscipit. Harum eum ut nisi. Pariatur sunt tempora similique et. Eaque aut quam dolorum tempore consequatur cupiditate odio. Rerum non hic et ipsum aut ab reprehenderit. Aut suscipit eveniet harum esse quos ex. Porro expedita dolor nihil tempore sint possimus. Architecto occaecati nulla repudiandae laborum. Nesciunt ipsam sed commodi consequatur. Et et vel iure laborum quisquam. Totam eligendi blanditiis enim aut. Quo nulla id repudiandae. Enim quis eum repudiandae dolores enim. Dolores at velit eius deserunt occaecati. Ut et ea iusto quod natus eum. Error libero qui voluptatibus sed similique et voluptatibus.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(13, 1, 'Assumenda amet vero incidunt eos.', 'assumenda-amet-vero-incidunt-eos', 'Dolorem nostrum aut sed voluptatem alias ipsam. Aliquam excepturi magnam voluptatem molestias. Ab at voluptas quasi. Id et veniam molestiae expedita molestiae ut odit. Quis tenetur minima eveniet omnis rem aliquam cum corrupti. Voluptates harum corrupti et voluptas. Magnam alias ratione quo sit saepe. Illo quo fugit quia aspernatur est hic. Et quos odit sit voluptatibus molestias. Quo earum sit quia omnis. Sit est voluptate quaerat non sit nesciunt blanditiis. Consequuntur quos ea similique quisquam minima. Esse sint quam dolores autem. Quia ut veniam dolorum non temporibus. Quod ratione fugit expedita facilis quo deserunt. Aut beatae expedita recusandae aut aut fugiat consequuntur. Omnis quia sit porro facilis ut excepturi eum. Iste ut quidem ut voluptas. Dolorem a aut saepe officiis. Molestiae aperiam nisi temporibus cupiditate nobis. Facilis qui pariatur magnam dicta hic et inventore. Quasi alias eligendi temporibus fugit excepturi ullam eligendi. Est porro quam itaque assumenda iste. Ut aspernatur quisquam voluptate voluptatem et excepturi. Placeat harum et consequatur rerum est aut. Corrupti illum voluptas quas maxime. Beatae et ut ea nostrum. Sed recusandae quod maxime ipsa consequatur qui. Voluptate minus doloribus voluptatem nostrum voluptatem tempora dolorum. Ea alias odit maiores. Unde nesciunt sequi recusandae quis explicabo et. Dolorum ut harum consequatur pariatur molestiae aut aut dolorum. Voluptate qui eum explicabo cumque esse est at. Exercitationem eos sed repellendus. Quasi beatae at ullam nisi. Consequatur ut voluptate sit. Dolorem consequatur nihil atque sequi nemo earum pariatur. Voluptate saepe corrupti vitae libero. Ab impedit ratione et unde omnis officiis. Hic doloremque consectetur aspernatur tenetur eveniet. Quo modi sed corrupti id beatae. Recusandae consequatur repellendus ipsum non architecto modi. Necessitatibus esse quo ducimus quae. Est maiores nobis voluptatibus velit dolor. Quam labore numquam est ipsum exercitationem at tempore. Culpa sed qui autem possimus voluptatem atque. Aspernatur unde vero repellendus laboriosam facere. Quas qui doloremque delectus veritatis ut maiores consequatur.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(14, 1, 'Placeat modi sed quia omnis.', 'placeat-modi-sed-quia-omnis', 'Iusto quia est aut. Dolor enim sequi quod adipisci molestiae odio corporis. Mollitia commodi maxime ut magni sed nesciunt. Ab non consequuntur voluptatem repellat optio voluptatem laboriosam. Vel quo reiciendis nobis voluptatem excepturi est vel et. Recusandae distinctio quod sit debitis. Voluptate quasi est dolores et necessitatibus quas sint. Et eum dolore quis nesciunt sed doloremque. Sit quis eius quos dignissimos. Debitis voluptate vel aut qui vero nihil voluptatem. In recusandae voluptas nulla repudiandae qui tempore. Qui velit quia quam consequatur voluptatibus suscipit illo qui. Repellat possimus aut praesentium illo qui sint sed. Ut vitae quo dolore dignissimos est quisquam officia deserunt. Veniam modi voluptatem amet officiis. Velit libero perspiciatis animi qui. Qui incidunt deserunt doloremque soluta. Est aut veniam error illum. Et vero enim quia. Dolores sunt hic recusandae distinctio labore. Doloremque voluptas ipsum illum facere eos voluptas aliquid. Fuga quia omnis odio beatae velit ullam asperiores officia. Aperiam impedit iusto aperiam maiores est aut iure. Autem aut consectetur voluptas. Laborum pariatur rem non ut facere blanditiis. Dolores et accusantium quibusdam soluta. Illum similique velit facere ut accusamus soluta. Vel rerum doloribus nemo et sunt. Nemo saepe dolor dolor odio excepturi. Est rerum debitis tempore eum officiis ut. At ipsa officiis ipsum laudantium voluptas debitis. Omnis et harum inventore ut. Fuga sed cum quod praesentium pariatur ut non. Sequi illo odio a eaque et rem quas. Consectetur placeat maxime illo nostrum rerum est. Quisquam ut facere fuga officia. Occaecati nam enim aut. Ut ad quam nulla vero laudantium iusto voluptates. Dolorum accusantium praesentium eius et qui tempore atque. Facilis dolorem maxime quia autem sed. Molestiae laborum quod consequatur iure. Iusto voluptate consequuntur repellat et aspernatur quia magni. Sequi mollitia delectus dolores voluptatibus voluptas veritatis. Illum blanditiis quia voluptatem iure. Nisi rerum quo dolorum quae reiciendis deserunt.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(15, 1, 'Eligendi incidunt corporis quia amet dolore.', 'eligendi-incidunt-corporis-quia-amet-dolore', 'Officia sequi quo quia odio nostrum. Reiciendis et culpa totam quia animi quia velit ullam. Dolorem aut aut quae excepturi eius sit soluta. Rerum sunt nihil optio sint. Ut ut laudantium dolorem nihil sed beatae est. Autem consequatur est rerum provident ut iure. Omnis commodi quidem in fugiat laudantium. Qui vel quisquam maxime assumenda. Ullam aut tempora sint esse. Aspernatur dolorum laborum quibusdam et nesciunt. Autem qui inventore id suscipit illum sint modi. Ducimus in consequatur ab veniam. Eos non esse facilis amet eum. Ducimus qui eos odit qui. Dicta perspiciatis consequatur velit sequi atque sit laborum. Doloremque a aut et esse qui qui quibusdam. Et sunt est blanditiis ex animi fugiat eos. Iure consequatur non consequatur dignissimos necessitatibus et quia. Ea veniam accusamus eligendi eum perferendis aliquam non pariatur. Necessitatibus consequatur accusamus quis dolorem nulla. Ut a nihil veniam perspiciatis velit fugiat. Possimus dolorem est tenetur exercitationem velit et. Et voluptatem tempora ipsam qui iste velit. Officiis qui ut odit quas. Ea possimus rerum animi perferendis nisi sint qui quae. Voluptas quis fugiat consectetur aut molestiae porro et dolores. Officia similique natus est quia. Enim at dolorum temporibus et necessitatibus. Et vel officia et impedit quaerat voluptas sequi. Et ducimus et ea non sunt. Nulla quia ea reiciendis possimus voluptates id quos voluptatem. Iusto omnis ut qui illo blanditiis debitis. In sed incidunt mollitia quisquam ut autem non aut. Consequatur eos beatae tempora optio ut et. Nam cupiditate odio nulla provident. Porro qui eius eum sit itaque explicabo. Cumque voluptatem animi praesentium ipsa laborum. Consequuntur accusamus est sunt sunt. Sit non veniam ut aut quaerat. Laborum non veniam officiis a quas doloremque sit eos. Cumque debitis nihil dolorem qui quos ut aperiam. Pariatur vel beatae explicabo. Molestiae aut pariatur qui pariatur non. Consequatur quae omnis dolorem fugiat unde possimus est. Ducimus iste voluptas illum quia quis ducimus. Dolor officiis aut beatae molestiae eos sunt cumque. Maiores amet sed omnis fuga sed delectus. Et enim occaecati maiores et. Harum ut nihil inventore iusto modi.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(16, 1, 'Et dolores iure dolor nesciunt aliquid tempore cumque sed.', 'et-dolores-iure-dolor-nesciunt-aliquid-tempore-cumque-sed', 'Ut sed quos vel qui. Hic aut delectus sit eaque ut. Quo voluptatibus nisi rerum facere. Ex deserunt blanditiis qui iste in. Accusantium nihil error unde consequuntur voluptatem voluptates. Nam sunt tempore ad aut doloremque sed. Voluptas tempora aut quis totam autem. A ea et atque id quas necessitatibus. Vel veritatis nihil in doloremque. Voluptas saepe eos aut sapiente. Eaque repudiandae et magni et. Et recusandae enim id id voluptatem est eum. Molestiae incidunt ipsam at autem et ut. Voluptatem accusamus perferendis error numquam dicta odit doloremque. Amet et quas illo. Ullam molestiae ea itaque magni officiis aut perspiciatis. Qui dolore culpa quam sequi. Qui sunt exercitationem aperiam dolorem aperiam qui doloribus. Quam ea quam architecto odio rerum ex possimus numquam. Hic distinctio pariatur distinctio et illum. Accusantium recusandae et dolor saepe quibusdam. Laudantium hic voluptates eum qui earum. Repudiandae velit enim inventore vero commodi. Sit atque alias sed qui laboriosam nemo. Saepe vel nulla nisi. Dolores quo deleniti excepturi qui. Nobis necessitatibus sed et id et ad. Suscipit et dolorem atque harum mollitia ut. Enim maxime minima nemo rerum ullam sequi. Placeat aut iste omnis et. Nam placeat aut est quod non. Voluptatem alias quia aut sit facere harum. Omnis veritatis eum temporibus vitae. Expedita velit reprehenderit voluptatem iure. Aperiam quaerat est voluptatem sit necessitatibus. Ut non nihil sapiente excepturi sit. Delectus et accusamus perferendis fugit debitis sit aut suscipit. Debitis debitis vero et corrupti eligendi quia laborum est. Consequatur quia fugit ut autem modi. Ea nesciunt earum voluptatem sed. Aut quam nam officiis neque voluptatibus est iure. Nam explicabo voluptatem architecto qui ad. Exercitationem quia ea doloribus iure. Possimus nisi quam sunt quis. Pariatur expedita qui sed velit aliquam temporibus totam. Vero nisi aut quae aut illo qui maxime ea. Quae ea exercitationem sit earum dolorem. Et officia sint est quis et. Qui sit fugit esse voluptatem quia et optio repellat.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(17, 1, 'Fuga et ut corporis et dolores.', 'fuga-et-ut-corporis-et-dolores', 'Optio minima repellendus explicabo est. Et quo nihil consequatur labore similique fugiat placeat vitae. Et autem laborum possimus recusandae est et est sed. Et esse dolores illum distinctio non architecto. Omnis architecto laborum officiis. Accusantium in recusandae tempora laudantium. Non voluptatum ea perferendis eum ipsa modi labore odio. Et in dolores inventore dolorem. Quae suscipit earum qui illo qui est vitae. Exercitationem provident voluptate velit aut delectus. Consequatur ut voluptatum laborum sequi. Dolor animi cupiditate est neque expedita aperiam autem. Placeat quia aliquid molestiae impedit fuga dolores nesciunt. Non repellat repellendus soluta. Facere et est maxime enim eius nulla odit. Cumque voluptatum consectetur quis tempore qui. Maxime harum deserunt magni incidunt doloremque. Ut quia repudiandae voluptas hic. Nobis labore perspiciatis expedita quam rem cum hic. Laudantium id doloremque ut id ratione in. Voluptatibus voluptates ut nobis id et. Deleniti sunt est aut laudantium nulla et quia odio. Voluptatem libero doloribus qui consequatur. Cupiditate voluptatem corrupti sed libero tempore. Odit aliquam earum magnam eum molestias. Voluptatem et non ratione. Eum eum nulla et praesentium qui accusamus repellat recusandae. Quidem fuga aut veniam est commodi. Mollitia adipisci architecto vel ipsa enim aut. Sunt quo quia quaerat temporibus. Itaque ipsum repellendus quia qui. Nobis est iste eligendi necessitatibus vitae ut adipisci. Ullam sequi quod voluptas. Est et corrupti possimus sequi necessitatibus eius provident. Quo fugit tempora minima officia architecto sed laudantium. Modi ea quia aspernatur veniam illo fugiat. Labore eius nisi quis est sed omnis adipisci. Voluptatem voluptatum qui iste. Saepe esse eligendi repellendus libero sit. Quis aliquid quae libero. Quis est et fugit. Ut perspiciatis dolorem voluptas ea facere. Eligendi recusandae in vel eius necessitatibus debitis. Dolorem qui vel minima et aut. Mollitia atque voluptate consequatur rerum. Voluptate dolor vero consequatur minima ut. Sed voluptatum debitis corrupti deleniti. Perferendis voluptas aut praesentium. Ab ipsa non atque mollitia.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(18, 1, 'Autem nobis voluptates iure laudantium.', 'autem-nobis-voluptates-iure-laudantium', 'Ducimus tempora aut quaerat sint. Adipisci aliquam quidem amet sint voluptate totam eum. Porro aut atque aspernatur optio nemo atque dolore. Autem quia in maxime sint perspiciatis iste labore. Enim quibusdam rerum officia quis et. Est consequatur doloremque eum ex. Suscipit velit et quod quia. Enim et quis iste et excepturi aspernatur. Nisi rerum similique suscipit itaque cum. Ut rerum voluptatem dolore. Exercitationem delectus maiores vel voluptatibus ad perspiciatis. Cupiditate odio et cum provident magni molestias sed. Neque et quia non et laudantium deserunt. Error sit modi molestias expedita tenetur repellat molestiae. Dolorum ex dicta laborum voluptatum dolorem doloremque. Quaerat cupiditate veritatis eum qui. Mollitia quas dolores consequatur dolor et consectetur. Sit harum et adipisci qui. Rem ducimus aut qui id non qui. Nam quam molestiae doloribus harum. Beatae aspernatur delectus ut quas. Aspernatur cumque dolorem qui pariatur. Eos aut minima aperiam quaerat aperiam commodi. Quos quibusdam velit non ad officiis molestias. Aut delectus incidunt et non neque. Iste velit eveniet repellendus architecto quas. Molestiae perferendis ducimus ut eveniet odio voluptatum pariatur aut. Blanditiis ratione quidem et dolor rem qui modi. Modi quos ut suscipit excepturi hic mollitia voluptatem. Rerum repellat eum tenetur est esse velit. Placeat vero sed voluptatem quia qui qui. Voluptatibus dolorum et accusamus optio reiciendis. Minima ea ut ex qui. Aut eaque voluptas expedita. Nostrum voluptatem fugiat quae occaecati dolore dolorum assumenda. Aspernatur recusandae sint amet quod ut. Facere voluptas quos fugit. Fuga et quia omnis et totam quidem ut. Esse dolores libero perspiciatis aut recusandae aut placeat saepe. Vero assumenda et soluta animi eveniet. Placeat fugit magni consectetur. Cum fugit nemo eum aut. Fugit id ex accusamus non quia. Sed explicabo voluptate maxime exercitationem fuga aut animi. Aut a ad qui autem vitae quaerat ut. Suscipit dolorem ad perferendis nam at ratione laudantium sit.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(19, 1, 'Ex et tempore amet consectetur aut.', 'ex-et-tempore-amet-consectetur-aut', 'Iusto vel delectus aperiam excepturi. Maiores et expedita unde ad natus aut voluptatem. Necessitatibus rerum animi nesciunt. Autem aut ea deleniti aperiam mollitia et. Ut recusandae consequuntur error consequatur quibusdam adipisci tempora inventore. Autem doloremque saepe laborum excepturi alias similique. A id veniam perferendis sit nemo est atque. Qui et aut labore. Corporis et incidunt consequatur molestiae officia. Neque voluptates nobis libero assumenda debitis. Molestias necessitatibus fugit molestias ut aut. Qui alias sapiente rerum perferendis molestiae. Beatae laudantium voluptatibus et qui. Et enim tempore earum aspernatur esse praesentium. Maiores voluptas consequatur est similique. Ab omnis sint neque ullam occaecati distinctio tempora asperiores. Doloribus optio non mollitia beatae sunt id. Voluptatem dolor voluptatem qui quidem. Laboriosam in porro dolor quos aliquam. Saepe voluptate asperiores eos quidem. Perferendis quod eius dolorum optio qui accusamus. Rem ex aut placeat autem recusandae et assumenda. Non reprehenderit vel est maxime. Necessitatibus possimus neque sequi. Quia itaque est sit rerum debitis nam. Nostrum enim optio sequi ratione omnis. Cumque sunt deserunt sequi quae. Assumenda asperiores sint eligendi deserunt eius dolor fugiat. Aut consequatur cumque enim provident hic iure fuga. Ex eius minima enim exercitationem aut sit aut. Voluptatem laborum accusantium at necessitatibus eum nemo dolore. Maiores eum dolorum inventore magni et dolorem ullam. Voluptates vitae aut exercitationem veritatis sed quia amet. Veritatis corrupti blanditiis debitis fugit quos vero qui. Non dolorem veritatis sequi officiis aut et qui corporis. Eligendi fugiat possimus quo ex nemo quaerat. A voluptatem rerum in repellat autem ab modi. Minus non dolores cum ut magni molestiae incidunt. Ut sed sunt ut. Harum facilis dolore sunt commodi saepe. Enim rerum enim provident dolor. Voluptas sed et deserunt aliquam modi accusamus. Officia est deserunt doloribus dolorem tenetur possimus ducimus. Non nisi quibusdam occaecati perspiciatis.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(20, 1, 'Saepe ipsam expedita et possimus quis ut.', 'saepe-ipsam-expedita-et-possimus-quis-ut', 'Aut vitae ut sunt soluta laborum maxime voluptate. Et ab sapiente quia temporibus soluta minus. Vel tempore voluptatum nulla et ab doloremque. Ut inventore sint nam. Esse cupiditate magni sit quaerat laudantium quidem repellat. Dolor ut ipsum sint repellendus sit nemo omnis. Autem perferendis eos sed voluptatem. Velit nesciunt tempore excepturi id asperiores cum est. Labore ut in quis mollitia sit ipsam. Magni tenetur id omnis impedit sed. Autem a molestias rerum ea ea dolor voluptatibus. Omnis et natus velit commodi. Odio aut repellendus sunt et illo vitae. Distinctio non sequi ducimus consequatur ea. Et occaecati nam officia aut ratione. A voluptatem omnis maxime. Facilis perspiciatis ut maxime. Facilis consequuntur iure vitae ratione quisquam. Voluptas maiores quis sapiente. Atque non blanditiis dolores adipisci nemo suscipit. Qui non optio nemo sunt hic possimus. Earum enim dolore quo et mollitia quod et ullam. Reiciendis omnis ipsa sit minus ipsa dolores saepe qui. Excepturi sed aliquid non reiciendis similique necessitatibus. Minus veritatis perferendis exercitationem nam qui. Aspernatur laboriosam vel excepturi velit. Placeat temporibus dolor corporis optio provident. Est sapiente omnis sint eos voluptas est sit reiciendis. Omnis itaque eveniet eum libero quia. Consequuntur a qui ut ut. Iusto porro quia in debitis. Libero et aut ea est dolorem. Quas animi soluta omnis esse consequatur cum. Corrupti nihil repellendus cumque modi officiis. Omnis ea reiciendis excepturi nisi quas fugit consectetur. Incidunt et et dolor ducimus voluptate odio. Libero illum quam est illum maxime consectetur. Voluptate dolores est enim beatae tenetur. Iure officiis fuga dicta. Voluptatibus sed non voluptate non veritatis enim explicabo. Tempora sit iste consequatur aliquid sit et veritatis. Deserunt dolorem quod autem quibusdam quo aut soluta et. Modi ipsum est inventore voluptas vel occaecati modi sint. Fugiat rerum qui id explicabo dolorum. Ullam omnis blanditiis et dolorum hic praesentium. Ut et id quidem ad qui et harum est. Voluptates eos dignissimos iure voluptate quis est saepe.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(21, 1, 'Saepe quia debitis blanditiis impedit ut.', 'saepe-quia-debitis-blanditiis-impedit-ut', 'Suscipit doloribus inventore ut hic vel consequuntur suscipit. Eos quas nihil omnis error nam est. Consequatur dolore minima et velit distinctio iusto. Et ea itaque fugit vitae deleniti odit cupiditate. Quis iusto dignissimos impedit tempore placeat laboriosam. In quisquam sunt est accusantium qui. Commodi quo veritatis ab dolores sed. Deserunt et necessitatibus rem ipsa. Et maxime temporibus dolorem dignissimos est et. Et nihil magni voluptate eligendi error eos ad voluptas. Eligendi quidem velit optio corporis et molestias necessitatibus. Molestiae sed consequatur minus non. Porro corrupti et quasi sed. Vel vel ea rem ea. Et assumenda deleniti quia velit modi vel. Eum iste molestiae ut cum esse. Ducimus deleniti modi ex aut dolores libero. Earum consequuntur consequatur enim ipsum labore saepe. Et quaerat incidunt quia quos. Deleniti et distinctio quis modi tempora. Natus natus quos eos et amet. Quos est sunt ratione culpa alias laudantium ad. Mollitia non enim expedita delectus. Eos in et molestiae. Voluptatem reprehenderit in et at veritatis. Quis rerum nisi odit eius eos ipsam. Minus eum accusamus incidunt nobis possimus ut. Nihil minus provident itaque et voluptates. Velit aut omnis non molestias dolorem illo. Aut sunt impedit fugiat officiis. Pariatur nihil velit natus quia et. Aut eos animi harum ducimus eum quam. Tempora alias eos cupiditate error. Est labore optio quia dolores. Sit ipsam deserunt quia delectus illo. Voluptatem sint sit aut. Minus in aperiam eum eum sit ex numquam. In assumenda ipsa amet aut atque. Sed quos et consequuntur consectetur possimus. Doloremque velit quod quis commodi maxime vel. Vel qui quia quos aliquid est. Omnis ea qui dolores quidem. Quam iusto non odit perferendis voluptas est eveniet. Eligendi earum temporibus dolor praesentium reprehenderit adipisci culpa harum. Suscipit temporibus minima rerum accusantium quae omnis. Unde odit accusamus id in fugiat numquam. Atque aut ipsam non voluptas. Rem id hic ad. Enim ratione et rerum nulla qui. Quibusdam asperiores natus rem temporibus iure delectus. Dolor molestiae deserunt quasi ea cumque soluta.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(22, 1, 'Veniam maiores quisquam dolores.', 'veniam-maiores-quisquam-dolores', 'Saepe repellat quam quo provident et. Consequatur doloremque occaecati natus in dolores est. Et explicabo laboriosam voluptas vero vel occaecati occaecati. Soluta qui ullam ipsa porro quam minus aut. Veritatis modi omnis illo facilis. Accusamus possimus adipisci et nulla. Minus at nobis accusamus doloribus. Dignissimos eveniet maxime et illo. Repudiandae quidem qui deserunt est dolorem praesentium consequuntur. Quae ut corrupti laboriosam animi aut et. Odio earum qui quo. Sit excepturi aut odit ab nobis atque. Voluptate sit similique temporibus consectetur. Qui rerum perspiciatis eius minus. Excepturi esse in consequuntur dolorum. Molestiae eligendi dolor voluptas. Non ipsum consequatur et qui. Nemo molestiae sit veritatis fugiat vel consectetur cum. Ut ad aut vitae natus. Illo ut consequatur at possimus. Explicabo consequatur ut aliquid qui est fugiat. Nesciunt consequatur voluptas magnam sint. Officiis debitis odit at maiores hic consequatur aut. Odit inventore pariatur eius incidunt laborum error. Voluptatem corrupti pariatur inventore. Velit eum inventore qui consequatur. In assumenda asperiores quaerat rerum. Ab totam et perspiciatis error accusantium. Voluptatibus pariatur doloremque similique. Provident laborum laudantium quis non rerum doloremque. Nihil voluptates culpa excepturi qui alias esse accusantium aut. In sunt sunt sint dolore et dolor consequatur. At hic aut iste et doloremque recusandae. Doloremque eaque illum iusto fuga quibusdam deleniti. Ratione voluptate provident corrupti aut qui vel. Corporis veniam dolorum officiis non eveniet ullam dolores dolorem. Provident molestias molestiae repellat harum eos eos. Voluptatum corrupti labore sed fugit. Fugiat soluta illum ea impedit et. Sed quos culpa molestiae ducimus exercitationem sunt. Eaque velit sunt qui repellat. Qui repudiandae nulla iusto nihil inventore omnis. Ut asperiores quo cupiditate consequatur qui ipsam. Maiores et quaerat saepe quasi dolore alias est. Voluptatem ea totam vitae id et nobis.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(23, 1, 'Vel commodi sed quasi maiores minus nobis.', 'vel-commodi-sed-quasi-maiores-minus-nobis', 'Nemo eum omnis ipsum aut fugit qui nihil. Quam fuga sit porro accusantium porro. Saepe ipsum quisquam dignissimos facere iste hic. Rem sit accusamus perspiciatis quod. Sed et sed nulla nobis. Laboriosam exercitationem ipsam ea iusto perferendis asperiores. Odio fugit nobis distinctio. Molestiae omnis quas veritatis repellat adipisci. Voluptatem est ut sequi et. Voluptatum temporibus tenetur et alias. Nisi qui nesciunt voluptatibus enim voluptatem cum. Est earum possimus veritatis optio tempore est quia. Ad necessitatibus qui ratione rem. Quo ut sit accusamus aliquid voluptates. Omnis maxime illum quisquam sit fugiat commodi. Corrupti fugit accusamus nobis sed ex ut delectus. Molestias nemo corrupti iste assumenda non. Aut itaque dolore dolorum nihil. Nihil molestiae qui omnis et nobis officiis illo recusandae. Aut qui asperiores distinctio. Laudantium excepturi harum eos et quis in. Numquam atque facere a sed explicabo sint. Qui dolor est impedit sit quia et. Ut eligendi ut voluptatem nostrum voluptate consequuntur magni. Voluptatem minima perspiciatis officiis et blanditiis est ut repudiandae. Voluptatum sunt tempora animi impedit assumenda omnis quia eos. Temporibus omnis voluptates nihil possimus distinctio pariatur. Enim earum omnis sint aliquam enim et magnam. Labore laudantium rerum sint eveniet. Unde ex molestiae velit. Voluptatem harum reiciendis quaerat. Neque occaecati exercitationem harum et. Dolorem deserunt itaque ut deserunt rerum. Sed velit possimus et recusandae. Quasi aspernatur necessitatibus impedit aliquam. Mollitia exercitationem itaque doloremque ipsam et eum ut minima. Commodi at autem eos. Rem nemo quasi maiores alias omnis. Eveniet laborum et quo sit fuga. Vel adipisci qui voluptatum esse consequatur quas voluptatem. Incidunt asperiores rem eveniet quia molestiae sit. Velit molestiae eaque et perferendis. Veritatis neque sapiente at rerum voluptatibus molestias. Deleniti voluptatem mollitia dignissimos asperiores. Quae alias non aperiam rerum. Deserunt porro pariatur qui aut omnis quia sunt aliquam. Ut et et facere explicabo necessitatibus. Sunt ullam nihil est aut alias nihil et.', '2024-03-15 04:48:38', '2024-03-15 04:48:38');
INSERT INTO `posts` (`id`, `user_id`, `title`, `slug`, `body`, `created_at`, `updated_at`) VALUES
(24, 1, 'Ut quas quam et repudiandae voluptas consequatur.', 'ut-quas-quam-et-repudiandae-voluptas-consequatur', 'At excepturi repellat deleniti non praesentium. Sit et molestiae aperiam sed amet repellendus molestiae ipsum. Sed qui consectetur pariatur in. Et aliquid sit tenetur perferendis alias enim in. Voluptas alias aperiam assumenda asperiores necessitatibus. Mollitia rerum quisquam eveniet voluptatem vitae omnis consequatur maxime. Repellat libero aut qui aut sint sunt. Dolores quidem hic quia dolorem nulla aut ex. Ut dolorem est ut in perspiciatis sint quibusdam iure. Nisi adipisci facilis explicabo dolores totam ea ut illo. Quos doloremque voluptas qui. Ducimus occaecati cupiditate ut aspernatur eum autem id autem. Nemo quia non aut commodi dignissimos cum magni consequatur. Autem facere alias non necessitatibus. Maiores autem nam quaerat iste. Sit illo alias fuga omnis est voluptatem. Molestiae eum excepturi amet ab et illum. Molestiae ipsum autem nemo explicabo ex. Quo voluptatibus sit aut amet. Sequi eum et perspiciatis explicabo harum enim. Quae exercitationem ut ut sit reprehenderit pariatur. Aut ea quasi reiciendis. Id maxime error iusto. Vitae atque delectus quia quibusdam. Praesentium vel repellat asperiores officia est quae. Neque cupiditate cum praesentium rem maxime autem. Sed quo sunt hic et totam nisi cumque. Soluta omnis accusantium aliquid aut in commodi beatae. Quam rerum id autem exercitationem. Magni qui similique inventore magnam. Rerum in et numquam nesciunt magni voluptatem architecto provident. Magni quaerat aut quaerat tenetur a. Possimus est explicabo dolor consequatur. Occaecati molestiae quis nobis officia est aspernatur consequatur. Officia est eligendi dolorem aut. Nam atque sunt eum eligendi ex. Dolores est ad dolor tempora ipsam. Dolorum hic consequuntur autem laboriosam quos. Possimus rem iste sed cumque. Suscipit fugit sit non quia sequi id accusantium. Unde illo dolor sed placeat non. Fugiat modi repellendus consequatur possimus. Cupiditate libero harum aut incidunt. Qui qui et ipsa modi tempore quae. Ipsam sed enim ullam commodi. Temporibus et consequatur iure eos. Rem excepturi enim provident rem repellendus qui omnis. Reiciendis doloremque aliquam dicta aut voluptatum beatae. Earum explicabo molestiae ad maxime omnis aspernatur.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(25, 1, 'Quia sed accusantium eius distinctio culpa.', 'quia-sed-accusantium-eius-distinctio-culpa', 'Aliquam non enim odio explicabo ut. Ratione animi autem minus vero consequatur est explicabo. Minus enim sit quisquam omnis quisquam voluptatem. Ipsa voluptate magni incidunt rerum est temporibus minima. Possimus commodi quia et laborum molestiae. Blanditiis quis consectetur illum voluptatem. Quaerat labore provident est id. Numquam et at et eveniet veniam molestiae autem. Maxime rerum optio itaque est quia. Inventore quibusdam est consequatur unde natus aut. Laborum quisquam autem dolores et sint deserunt ullam. Suscipit laboriosam officia commodi voluptatem accusantium. Facere minus sit quo ratione molestiae et qui distinctio. Cumque excepturi facere aut et necessitatibus ipsum deserunt et. Voluptas ea soluta reiciendis dolorem inventore odit. Cum ad rerum ratione ut dolorem eum ad. Ducimus eos dicta qui sunt. Vel nam eveniet sed. Cupiditate fugiat aut perspiciatis optio aut sed voluptatem quod. Sunt neque sapiente unde. Deserunt unde nisi laboriosam dolorum. Consequatur illo officiis dolores et et reprehenderit. Veritatis exercitationem nostrum temporibus exercitationem. Architecto iste perspiciatis pariatur. Et et consequatur libero nemo explicabo ratione nesciunt. Voluptatem reiciendis id et expedita harum dolore autem ex. Eum sit tempore cum. Nihil et saepe labore omnis odit ipsum. Deleniti sapiente recusandae itaque tempore repudiandae nam. At et laudantium placeat. Aut voluptatum aut illo doloremque hic. Cum ut commodi earum esse. Illo minus aliquam sed sed. Ipsa nihil culpa adipisci architecto corrupti. Nesciunt doloribus dolorem rem quo dolorem perspiciatis. Ex non impedit nemo. Earum minus et debitis unde. Reprehenderit quibusdam placeat ea consequatur quo id. Possimus repellendus commodi sunt est. Doloribus ratione sint doloribus et dolorum odio. Architecto cum placeat commodi pariatur exercitationem. Voluptate aliquam dolore et non dolor id. Architecto alias nemo nesciunt corrupti cumque perferendis quia distinctio. Amet non quo deleniti voluptatibus quod sed reiciendis. Tempora non ipsum enim aut. Labore iure quo blanditiis eum ut ea soluta ut. Distinctio et est deserunt ullam. Nam reiciendis architecto tempore veniam sint voluptatibus.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(26, 1, 'Et rem nesciunt quae recusandae ab.', 'et-rem-nesciunt-quae-recusandae-ab', 'Eum dolorum sit dolorum quia. Quae omnis qui voluptatem at quia corporis. Ipsam dolorem qui velit iste aliquid. Impedit nesciunt voluptatem aut aut. Et minus non eligendi molestiae. Nesciunt rerum ipsum ut non sequi aperiam. Consequatur sit porro deleniti ut. Placeat quas voluptate et molestias. Hic placeat ea aut. Maxime reiciendis tenetur sunt quae consequuntur delectus et. Illo magni odit voluptatem veniam. Rerum laudantium officiis assumenda sapiente sint harum autem. Et quis accusamus ipsum sit voluptatem quam et. Labore a repellat et qui in necessitatibus sed. Esse repellat aliquid sint odio vitae. Qui iure similique quaerat alias. Eos totam tempore sit dolor inventore et. Animi dolorem ea labore et at impedit. Laboriosam eius aut quis cum. Et ipsa possimus magnam consequatur et. Officia id necessitatibus esse distinctio unde a sit. Est necessitatibus quis omnis aut. Amet assumenda qui ad expedita. Quos quis doloremque qui autem non hic itaque. Rerum at necessitatibus voluptates saepe repellendus vel at expedita. Reiciendis molestiae dolorem sit omnis voluptatem rerum. Similique dolorem est officia et impedit quam. Repellendus maxime tenetur reprehenderit et nisi ipsa. Rerum quo cupiditate culpa laborum. Sapiente quam delectus quos odio. Natus sunt non et qui doloribus et ducimus. Officiis qui at sed voluptas error voluptas cum aliquid. Nihil illo omnis perferendis inventore corrupti. Cupiditate ut velit culpa est. Repudiandae aliquam autem sunt nesciunt. Fuga sed ipsam quisquam maxime. Quae minima illum et facere. Cumque dolores magnam doloremque ad libero. Consectetur unde minima qui consequatur accusantium laborum. Eum repellendus numquam deleniti totam id. Consequatur architecto enim ullam id quisquam facere laborum. Molestiae et modi iusto aut suscipit veniam. Repellat in deleniti recusandae vel fugit delectus et. Aut quo occaecati alias autem expedita omnis. Praesentium molestias et exercitationem totam ullam dolore. Odit veniam tempora repudiandae. Modi facilis perspiciatis possimus labore. Molestiae quo repudiandae vel harum provident eos. At corrupti rem nesciunt et dicta. Aut eveniet assumenda quia excepturi.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(27, 1, 'Praesentium aperiam laboriosam qui dolor nam amet.', 'praesentium-aperiam-laboriosam-qui-dolor-nam-amet', 'Rerum ut eius expedita et ut cumque. Ut magni minus dolor odio est illum. Impedit ea dolorem nesciunt ut nisi. Aliquid minus molestias nemo labore aut velit voluptatem asperiores. Itaque reprehenderit ratione voluptatem quaerat fugiat non. Iure aut numquam in excepturi eos reprehenderit. Quae consequuntur perspiciatis ullam inventore inventore consequatur rerum. Recusandae saepe sunt sit error nam repellendus. Unde est porro nihil pariatur. Ad explicabo ut mollitia quia ut odit. Debitis non animi quaerat provident. Qui laboriosam doloribus nam cupiditate. Dolorem id ut culpa facilis et. Incidunt ipsum sed nisi rerum minima temporibus. Veritatis doloremque aut repellat sed temporibus mollitia. Sint eos id reiciendis omnis sed doloribus doloribus. Veniam quam eaque blanditiis corrupti dolor. Quo dignissimos magnam maiores est est. Eos velit inventore minima dicta blanditiis. Sapiente dolores quisquam consequuntur ad. Quam rem nihil quae nulla quia delectus. Corporis occaecati cupiditate ea neque consectetur aut iste. Deleniti ratione pariatur rerum at. At vel velit qui quod. Labore rerum itaque molestias fugiat sed illum error possimus. Facilis repudiandae quisquam voluptatum omnis enim. Quasi tenetur sapiente voluptate tenetur nisi amet. Non architecto mollitia consequatur et qui consectetur. Sit commodi aut sunt sit sed. Qui autem rerum velit sequi aut. Voluptas consequatur qui delectus maiores qui qui. Quo voluptatem impedit aperiam distinctio consequatur possimus. Dolore et inventore ullam vero id. Atque illo id dicta adipisci eveniet. Ut aut voluptatum dolorem maiores. Ut rerum laudantium et. Tempora sint necessitatibus eos ut. Odit enim reprehenderit ea et aut. Ducimus necessitatibus amet maiores quae itaque consequuntur nemo. Et qui velit aperiam ipsa molestiae quas. Voluptatem ad modi odit sunt eum. Eos qui esse recusandae veritatis voluptas tenetur ullam. Exercitationem tempore esse quia vero. Et dolores enim rerum voluptates aliquam. Et reprehenderit saepe magnam accusantium quo adipisci. Non aut a sit occaecati voluptatem enim. Voluptas qui ea voluptatem a nihil ea sed.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(28, 1, 'Nihil ipsum vel non omnis consequatur.', 'nihil-ipsum-vel-non-omnis-consequatur', 'Eos adipisci odit sed dignissimos. Tempora distinctio dicta labore vel sed error. Fugit consequatur non pariatur inventore. Fugiat velit et neque iure. Unde dolores iure ipsam quia et quia. Perspiciatis quae deleniti ducimus non nostrum placeat occaecati. Fugit ut ut labore qui aut deserunt ipsa. Quia corporis minima autem ipsam alias illum aperiam. Quas culpa sed harum aut hic fugit numquam quod. Ipsam blanditiis sit et cupiditate. Consectetur non cupiditate vel rem. Dolorem molestiae ipsum illo. Distinctio amet iusto quia possimus harum sit aut. Veritatis accusamus reiciendis fuga et eos. Deserunt molestiae laboriosam illum recusandae aut quisquam iusto aut. Earum aspernatur nisi nam amet qui ratione. Veritatis animi dolor dolores ducimus aut. Doloribus perspiciatis dolorem et illum dolorem. Sed qui id explicabo reprehenderit sit amet exercitationem. Tempore eos doloribus impedit et vitae eaque quos. Ducimus deserunt eos placeat. Autem deserunt non non autem. Non perferendis facere ipsum provident rerum voluptates illum. Rerum eos enim atque dolor voluptatem nam cupiditate. Qui autem aut sunt exercitationem ut. Aspernatur error mollitia unde sit repellendus. Doloremque dicta nobis voluptas eius laudantium aperiam ex. Et itaque dolores consectetur accusantium. Aut sunt eum laboriosam aut nostrum est. Quidem eos quas illo quas laudantium magnam id vel. Ea corporis sed sed sit. Et pariatur quis nihil tempora. Tempore id ut id quidem veniam fuga. Qui aliquam ea repellat corrupti. Error repellendus rerum dicta officiis molestias esse est. In molestiae recusandae quisquam. Repellat qui minima maxime vel quo. Assumenda aut est voluptatem nostrum. Voluptatum magni aut voluptatem. Quod eos atque facere a. Libero et excepturi nobis aut est. Est atque minus quae quia deleniti aut voluptas. Hic tempore dolores sed hic eaque ut. Consectetur placeat cumque ut est dolores quia aut. Nesciunt quibusdam officia dignissimos reiciendis impedit. Magnam laudantium cumque et illo. Explicabo magnam illum placeat mollitia nisi sed iure. Veritatis adipisci qui minima omnis. Ut tenetur veniam fugiat. Deserunt quia minus asperiores inventore.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(29, 1, 'Natus rerum dolores sit quidem sed aut ea.', 'natus-rerum-dolores-sit-quidem-sed-aut-ea', 'Voluptatum cum voluptatem modi in sed. A inventore voluptatem et necessitatibus. A non natus omnis aut quisquam at laboriosam. Est ea nulla exercitationem. Quisquam fuga enim adipisci dignissimos. Omnis minima adipisci beatae aliquam ducimus nesciunt et tenetur. Ab voluptatem odio voluptates et qui. Ipsum velit et alias ex. Aut iste quo quaerat dignissimos in ea. Qui omnis delectus aut et sit saepe cum consequatur. Corporis minima et omnis voluptatem aspernatur. Vel vero placeat quia assumenda aliquam ea in. Distinctio blanditiis voluptatem sit consectetur est. Porro unde optio a aliquid. Cupiditate eius incidunt id. Alias ipsum voluptatem non et rerum animi. Rerum laboriosam in explicabo. Sit animi et ut dignissimos. Eveniet rerum omnis voluptate quia voluptatem sit. Delectus deleniti vitae voluptatem necessitatibus. Laborum amet debitis molestiae enim tempore modi saepe. Ea rerum et qui ut temporibus totam soluta repudiandae. Qui dolor qui est ut. Qui natus consequatur repellat libero sit qui quaerat iste. Atque illum est sed rerum itaque laborum et provident. Sed nemo quasi iure voluptatem voluptates sunt. Enim facilis rem a aliquam aut consequuntur quia. Et et iure soluta deleniti deserunt error adipisci. Officia ut earum iure id est. Sint odit sed saepe assumenda sed. Est modi qui repellat nam. Iste sed labore praesentium nemo. Qui quas dolorem veniam sed. Aspernatur suscipit dolore et id. Cumque reiciendis tempora velit quisquam dolores. Rerum voluptatem natus quae est minima cum quibusdam voluptatem. Qui voluptas assumenda voluptatibus laboriosam. Sed consequatur optio consectetur rerum. In quasi excepturi est et. Dolores esse molestiae nemo non veritatis hic. Tempora voluptatem qui voluptatibus ipsa rerum est quis. Eveniet sit velit distinctio magni. Possimus consectetur numquam perferendis nihil. Nostrum debitis et aut nulla voluptatum. Vitae odio qui qui quod. Molestias fugiat ut alias dolore fugit. Et vitae soluta consequatur a non sunt adipisci. Quos nobis dolorem doloribus non. Tenetur possimus quidem aut quis assumenda voluptatem. Qui illum a nam.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(30, 1, 'Tenetur provident et et asperiores et ea.', 'tenetur-provident-et-et-asperiores-et-ea', 'Fuga aut vero soluta totam. Sit ea et accusantium ea numquam rem et. Cum minima ad dolore commodi voluptatem. Nostrum ut minima soluta fuga. Ad quaerat officia harum quia tenetur nobis iure. Aut ducimus vel sunt quidem. Repellat iste aspernatur accusamus. Qui est optio rerum et rerum omnis. Dolorum est doloremque sit. Perspiciatis magni nisi explicabo sed id adipisci. Eveniet aut fuga sint ipsum veritatis odit doloribus facere. Impedit officiis neque deserunt nihil velit consequatur. Suscipit deserunt inventore odit aperiam itaque quia rerum. Voluptatem necessitatibus aut quaerat aut sunt voluptas. Cumque ducimus doloribus explicabo omnis occaecati. Impedit sed labore architecto nobis amet voluptas. Similique vero qui ipsa sequi et. Corporis quod ipsam aut quo at. Sint nesciunt voluptatum voluptatem illum. Sunt voluptate sint est culpa aut quia consequuntur iste. Ut fugiat eos molestias vel occaecati. Asperiores ipsam dolor laudantium nihil illum aliquam qui voluptatem. Dicta numquam perspiciatis dolorum. Aspernatur beatae nobis et. Non laborum voluptate vel corporis. Itaque nesciunt iure quia ab voluptas ullam. Facilis architecto ratione placeat quisquam odit quia et consequuntur. Labore est quo veritatis rem qui consectetur. Dolorum quis provident et perspiciatis perspiciatis et in. Omnis cumque sint optio tenetur sed doloribus inventore. Voluptate totam eum repudiandae officia laudantium occaecati. Laboriosam sequi dolore est voluptas. Vero quia eius libero odio inventore sit. Sed hic ea quisquam quaerat enim et quia. Dignissimos qui exercitationem rerum consequatur commodi hic. Ut laboriosam ut optio pariatur ipsum aut. Provident error quia praesentium voluptatem et. Explicabo ut in consequatur rem. Dolorem amet et aperiam. Ea nemo natus assumenda ea maxime deleniti. Modi labore minus quis modi odit quia in esse. Culpa delectus maxime ut distinctio placeat ipsa. Sequi non excepturi cupiditate ut vero enim accusamus. Neque quia voluptates sint delectus. Enim autem sed dolores quis. Et mollitia praesentium reiciendis excepturi sint. Et et natus repellendus corrupti quis. Veritatis tenetur eos nesciunt eveniet. Sint id a natus fugiat molestiae.', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(31, 2, 'Rock', 'Rock', 'Rock music, often simply referred to as rock, is a genre of popular music that originated as \"rock and roll\" in the United States in the late 1940s and early 1950s. It has since evolved into a broad musical style characterized by a strong emphasis on electric guitars, bass, drums, and often keyboards. Rock music typically features a verse-chorus form and is known for its powerful rhythms, catchy melodies, and expressive lyrics.\r\n\r\nThroughout its history, rock music has diversified into numerous subgenres, each with its own distinctive sound and characteristics. Some of the most notable subgenres of rock music include:\r\n\r\nClassic Rock: Originating in the 1960s and 1970s, classic rock includes iconic bands such as The Beatles, Led Zeppelin, The Rolling Stones, and Pink Floyd.\r\n\r\nHard Rock: Known for its heavy, distorted guitar sound and aggressive lyrics, hard rock bands include AC/DC, Deep Purple, and Guns N\' Roses.\r\n\r\nHeavy Metal: Characterized by its intense guitar riffs, fast tempos, and often dark or controversial themes, heavy metal bands include Black Sabbath, Iron Maiden, and Metallica.\r\n\r\nPunk Rock: Known for its raw, DIY ethos and rebellious attitude, punk rock bands include The Ramones, The Sex Pistols, and The Clash.\r\n\r\nAlternative Rock: Emerging in the 1980s and 1990s as an alternative to mainstream rock, alternative rock bands include Nirvana, Pearl Jam, and Radiohead.\r\n\r\nGrunge: A subgenre of alternative rock that emerged from the Seattle music scene in the early 1990s, grunge bands include Nirvana, Soundgarden, and Alice in Chains.\r\n\r\nIndie Rock: Characterized by its independent, often underground ethos, indie rock bands include Arcade Fire, The Strokes, and Vampire Weekend.', '2024-03-15 05:45:13', '2024-03-15 05:46:14');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'Cesar Alvarez', 'cesaram34313@gmail.com', '2024-03-15 04:48:38', '$2y$12$aSArK.XQCoKlQym0t4C/BeUKg49HDeLRW8Zy1DZ9PoBvihvlANZHO', 'a4GoxWy1snu4GlMwCopGGq5GOnJEiTkkZUXmzjWBB2XIHaOsuJ2FoNpZBmsY', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(2, 'Mr. Oral Williamson Jr.', 'royal13@example.net', '2024-03-15 04:48:38', '$2y$12$aSArK.XQCoKlQym0t4C/BeUKg49HDeLRW8Zy1DZ9PoBvihvlANZHO', 'XTqJLcYCrOq1Aqoax3BGSf7VpGTYFUiLoRDD8OEM1bnHoE7xenfKUzRdNY85', '2024-03-15 04:48:38', '2024-03-15 04:48:38'),
(3, 'Kevin', 'cesaralvarezuchiha3@gmail.com', NULL, '$2y$12$hbVWK3hwgenOFlhDkbeHq.jt3KhMjqkFbzcq9pulCuf352gjqa8ve', NULL, '2024-03-16 22:54:23', '2024-03-16 23:01:21');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`);

--
-- Indices de la tabla `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `password_reset_tokens`
--
ALTER TABLE `password_reset_tokens`
  ADD PRIMARY KEY (`email`);

--
-- Indices de la tabla `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  ADD KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`);

--
-- Indices de la tabla `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `posts_slug_unique` (`slug`),
  ADD KEY `posts_user_id_foreign` (`user_id`);

--
-- Indices de la tabla `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=34;

--
-- AUTO_INCREMENT de la tabla `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `posts`
--
ALTER TABLE `posts`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;

--
-- AUTO_INCREMENT de la tabla `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `posts`
--
ALTER TABLE `posts`
  ADD CONSTRAINT `posts_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
